/* Auto-generated by genmsg_cpp for file /work/ros/pkgs-trunk/point_cloud_perception/pcl/msg/PolygonMesh.msg */
#ifndef PCL_MESSAGE_POLYGONMESH_H
#define PCL_MESSAGE_POLYGONMESH_H
#include <string>
#include <vector>
#include <ostream>

// Include the correct Header path here
#include "sensor_msgs/PointCloud2.h"
#include <pcl/Vertices.h>

namespace pcl
{
  struct PolygonMesh
  {
    ::sensor_msgs::PointCloud2 cloud;
    std::vector< ::pcl::Vertices>  polygons;
  }; // struct PolygonMesh

} // namespace pcl

#endif // PCL_MESSAGE_POLYGONMESH_H

